var TABS=[["p-start","Start"],["p-hw","Hardware"],["p-points","Points & Motors"],["p-bridle","Bridle Math"],["p-fly","Fly Systems"],["p-truss","Truss & Loads"],["p-safety","Safety"],["p-sim","Simulators"],["p-drills","Drills"],["p-scen","Scenarios"]];

var CARDS=[
["What does WLL mean?","<b>Working load limit</b> &mdash; the most you may put on a part in service. WLL = minimum breaking strength &divide; design factor."],
["What is a design factor?","The margin between breaking strength and WLL. <b>5:1</b> is the common minimum for rigging hardware and slings. It is already inside the WLL."],
["A sling is rated 3,500 lb WLL and the leg tension is 3,200 lb. OK?","<b>Yes.</b> The design factor is already in the WLL. Dividing by it again is double-counting."],
["What actually reduces a WLL?","The <b>hitch</b> (choker, basket), the <b>angle</b> (sling angle, side-loaded shackle or eye bolt), <b>shock loading</b> and <b>damage</b>."],
["Anchor (bow) shackle vs chain (D) shackle?","<b>Bow:</b> round, takes multiple legs &mdash; the arena standard. <b>D:</b> straight, for a single in-line pull only."],
["Two bridle legs and a motor hook on one shackle &mdash; what goes where?","<b>Legs in the bow, hook on the pin.</b> Keep the included angle in the bow at or under 120&deg;."],
["What is mousing?","Seizing a shackle pin with wire or a tie so vibration or rotation can't back it out."],
["Side-loaded shackle at 90&deg; &mdash; roughly what capacity?","About <b>50%</b> of WLL on a common manufacturer table (about 70% at 45&deg;). Keep shackles loaded in line."],
["Typical WLL of a 5/8&Prime; screw-pin anchor shackle?","<b>3&frac14; t</b> &mdash; but always read the bow."],
["What is &ldquo;steel&rdquo; in an arena?","Wire-rope slings with eyes both ends, in standard lengths, combined to make baskets and bridle legs."],
["6&times;19 &mdash; what do the numbers mean?","<b>6 strands, 19 wires per strand.</b> 6&times;37 is more flexible but less crush- and abrasion-resistant."],
["What is IWRC?","<b>Independent wire rope core</b> &mdash; a small wire rope at the centre. Holds its shape under load and crushing better than a fibre core."],
["Why softeners on a beam?","Flange edges cut steel and slings. Burlap, sleeves or pads at every edge the sling touches."],
["Steel with a kink in it?","<b>Tag it out.</b> Kinks, birdcaging and crushing are permanent damage. It does not get straightened and reused."],
["Round sling colours: purple, green, yellow &mdash; vertical WLL?","<b>Purple 2,600 lb &middot; green 5,300 &middot; yellow 8,400.</b> (WSTDA code &mdash; always confirm on the tag.)"],
["Round sling in a basket &mdash; does it double?","Only when both legs hang <b>vertical</b>. Spread the legs and the angle factor takes it back."],
["Round sling with no tag?","<b>Out of service.</b> The tag is the rating. No tag, no lift."],
["Which chain grades are for overhead lifting?","<b>Grade 80 and 100 alloy</b> only. Grade 30, 43 and 70 are not, however thick."],
["Up rigger vs down rigger?","<b>Up:</b> in the steel &mdash; baskets, builds the point, tied off 100%. <b>Down:</b> on the floor &mdash; marks, builds bundles and bridles, sends hardware up, hangs motors."],
["What does &ldquo;Rope!&rdquo; mean?","A line is about to be dropped from above. Clear the area under it."],
["What do you do when someone yells &ldquo;Headache!&rdquo;?","<b>Don't look up.</b> Cover your head and move out from under the work."],
["What is two-blocking?","The hook block running into the hoist body at the top of travel. It can break the chain. The upper limit switch prevents it."],
["Chain motor runs DOWN when you press UP. What now?","<b>Stop.</b> It's out of phase &mdash; and on a reversed motor the <b>limit switches won't protect you</b>. Fix the phase at the controller or cable."],
["Climbing motor vs body-up?","<b>Climbing:</b> motor on the truss, hook to the point, motor climbs its chain. <b>Body-up:</b> motor hangs from the point, hook lifts the load."],
["D8 vs D8+ hoist?","<b>D8+</b> has redundant brakes and a higher design factor and can hold a load over people. A <b>D8</b> over people needs a secondary safety."],
["Bridle leg length formula?","<b>L = &radic;(h&sup2; + v&sup2;)</b>. h = horizontal to the beam, v = vertical drop. Round up to the steel and chain you have."],
["Which bridle leg carries more weight?","The leg <b>closer</b> to the load (shorter horizontal distance). Its share = W &times; (other leg's h) &divide; (h1 + h2)."],
["Bridle leg tension formula?","<b>T = V &times; L &divide; v</b> &mdash; the leg's share of the weight, times leg length over vertical drop."],
["Maximum bridle included angle?","<b>120&deg;.</b> At 120&deg; each leg carries the full load. Past it, each leg carries more than the load."],
["Sling angle factor at 30&deg;, 45&deg; and 60&deg; from horizontal?","<b>2.0, 1.41, 1.15.</b> Factor = 1 &divide; sin(angle)."],
["Counterweight loading order?","<b>Batten first, then arbor.</b> Unloading: <b>arbor first, then batten.</b> Never let the arbor outweigh the batten during loading."],
["What is a runaway?","An out-of-balance set moving on its own &mdash; usually an arbor-heavy set flying out when the lock is released."],
["Is a rope lock a brake?","<b>No.</b> It holds a balanced set. It is not designed to hold a set badly out of balance."],
["Short line, centre line, long line?","Lift lines named by distance from the head block. <b>Short line</b> is nearest the fly-gallery side."],
["Double purchase &mdash; what changes?","The arbor travels <b>half</b> the batten's distance and carries <b>twice</b> its weight. Theoretical MA 2:1 at the arbor."],
["What goes in the fire curtain's path?","<b>Nothing.</b> Ever. It has to drop by gravity all the way to the deck."],
["UDL vs point load on truss?","<b>UDL:</b> spread evenly &mdash; usually the highest rating. <b>Point load:</b> concentrated &mdash; a single centre load is the worst case."],
["Bent diagonal on a truss section?","<b>Out of service.</b> Aluminium is never straightened and reused. Engineer or manufacturer decides."],
["Dynamic load factor?","<b>DLF = 1 + a &divide; g</b>, g = 32.2 ft/s&sup2;. Any start, stop or bounce adds load."],
["Wind pressure formula?","<b>q = 0.00256 &times; V&sup2;</b> (psf, V in mph). 60 mph &asymp; 9.2 psf."],
["OSHA fall protection heights?","<b>4 ft</b> general industry &middot; <b>6 ft</b> construction &middot; <b>10 ft</b> scaffolds."],
["Fall arrest anchorage strength?","<b>5,000 lb per person</b>, or engineered for the job."],
["What is suspension trauma?","Hanging still in a harness after a fall &mdash; blood pools in the legs and you can lose consciousness within minutes. Plan the rescue <b>before</b> anyone goes up."],
["OSHA reporting deadlines?","<b>Fatality: 8 hours.</b> Hospitalisation, amputation, loss of an eye: <b>24 hours.</b>"],
["Hierarchy of controls?","<b>Eliminate &rarr; substitute &rarr; engineer &rarr; administrative &rarr; PPE.</b> PPE is the last line, not the first."]
];

var QS=[
{q:"A chain motor is rated 1 ton (2,000 lb) WLL. You need to fly 500 lb over the audience. Is the motor adequate on capacity?",
  o:["No — multiply 500 by 7 for people below","Yes — the design factor is already in the WLL; 500 lb is well under 2,000","Only at half speed","Only with a load cell"],a:1,
  e:"<b>WLL already includes the design factor.</b> 500 lb on a 2,000 lb WLL hoist is within rating. Over people, what matters is the hoist's <b>class</b> (D8+ or a secondary safety), not re-dividing the WLL."},
{q:"Two bridle legs and a motor hook go on one anchor shackle. Where does each go?",
  o:["Legs on the pin, hook in the bow","Legs in the bow, hook on the pin","One leg on each side of the pin","It doesn't matter if the shackle is big enough"],a:1,
  e:"<b>Multiple legs in the bow, single piece on the pin.</b> Legs on the pin side-load it and spread it. Keep the included angle in the bow at or under 120°."},
{q:"Symmetrical bridle: 2,000 lb load, each beam 8 ft horizontally from the apex, 6 ft drop. What is each leg's length and tension?",
  o:["10 ft, 1,000 lb","10 ft, about 1,667 lb","14 ft, about 1,333 lb","8 ft, 2,000 lb"],a:1,
  e:"L = √(8² + 6²) = <b>10 ft</b>. Each leg's share = 1,000 lb. T = 1,000 × 10 ÷ 6 = <b>about 1,667 lb</b>. Flat legs (8 across, only 6 down) cost a lot of tension."},
{q:"Unequal bridle: 1,200 lb, apex 4 ft from beam A and 8 ft from beam B, 6 ft drop. Which leg carries more of the weight, and how much?",
  o:["Leg B — 800 lb","Leg A — 800 lb","They split it 600 / 600","Leg A — 400 lb"],a:1,
  e:"Share A = 1,200 × 8 ÷ (4 + 8) = <b>800 lb</b>. The leg <b>closer</b> to the load carries more. Its tension = 800 × √(4²+6²) ÷ 6 = about 961 lb."},
{q:"At what included angle does each leg of a symmetrical bridle carry the full load?",
  o:["60°","90°","120°","180°"],a:2,
  e:"<b>120°</b> included = 30° from horizontal; 1 ÷ sin 30° = 2, times half the load = the whole load in each leg. That is the limit — past it, each leg carries more than the load itself."},
{q:"A purple round sling (2,600 lb vertical) is used in a basket with both legs hanging vertical. Capacity?",
  o:["1,300 lb","2,080 lb","2,600 lb","5,200 lb"],a:3,
  e:"A basket with <b>vertical</b> legs doubles the vertical rating: <b>5,200 lb</b>. Spread the legs and the sling angle factor reduces it. A choker is about 80% of vertical."},
{q:"A round sling's cover has a cut and you can see core yarns. The tag is fine. Decision?",
  o:["Keep it — the core carries the load","Tape over it and use it for light loads","Tag it out","Use it on the ground only"],a:2,
  e:"<b>Tag it out.</b> The cover protects the core from cuts, abrasion and UV. Once the core is exposed, nobody can vouch for the rating."},
{q:"You press UP on a chain motor and it runs DOWN. What's the right move?",
  o:["Use the DOWN button to go up for now","Stop, and get the phase corrected before running it again","Swap the chain bag","Run it to the lower limit to reset it"],a:1,
  e:"<b>Stop.</b> A reversed motor is out of phase, and its limit switches won't protect it — it can two-block or run off its chain. Correct the phase at the controller or cable."},
{q:"What is two-blocking?",
  o:["Two motors on one controller","The hook block hitting the hoist body at the top of travel","Two shackles in series","A bridle with two legs"],a:1,
  e:"Two-blocking drives the hook into the body; the force can break the chain or the hook. The <b>upper limit switch</b> exists to stop it. Never bypass a limit."},
{q:"Loading a counterweight set for the first time. What order?",
  o:["Counterweight first, then the batten load","Batten load first, then counterweight","Both at the same time","Whichever crew is ready first"],a:1,
  e:"<b>Batten first, then arbor.</b> The batten is down and the arbor is up at the loading gallery. If the arbor gets heavier than the batten, it falls and the batten flies out — a runaway."},
{q:"Scenery has just been taken off a batten but the arbor still has its full counterweight. Someone reaches for the rope lock. What do you say?",
  o:["Go ahead, it's empty now","Stop — the set is arbor-heavy; weight comes out of the arbor before that lock comes off","Pull it slowly","Only if two people hold the rope"],a:1,
  e:"The set is now badly <b>arbor-heavy</b>. Releasing the lock is a runaway. When unloading, <b>counterweight comes off first</b>, then the batten load."},
{q:"Short line, centre line and long line on a line set are named by:",
  o:["Their distance from the head block","Upstage to downstage order","The weight they carry","The length of the batten"],a:0,
  e:"Lift lines are named by their distance from the head block. The <b>short line</b> is nearest the fly-gallery side, the <b>long line</b> farthest."},
{q:"A section of box truss has a bent diagonal. Correct action?",
  o:["Straighten it and use it at half load","Use it at the end of a run where loads are low","Out of service until the manufacturer or an engineer says otherwise","Tape it so it's visible and keep going"],a:2,
  e:"<b>Out of service.</b> Bent or dented members change how the truss carries load, and aluminium is never straightened and reused."},
{q:"A 40 ft truss hangs on four evenly spaced motors with 20 lb/ft spread along it. Roughly what does each interior motor carry from that spread load?",
  o:["200 lb","About 267 lb","400 lb","800 lb"],a:1,
  e:"Spacing ≈ 13.3 ft. Each interior motor carries its tributary zone — half to each neighbour: 13.3 × 20 ≈ <b>267 lb</b>. End motors get about 133 lb. Then add motor, chain and cable."},
{q:"A chain hoist accelerates a 1,000 lb load at 4 ft/s². Effective load?",
  o:["About 1,000 lb","About 1,124 lb","About 1,500 lb","About 4,000 lb"],a:1,
  e:"DLF = 1 + 4 ÷ 32.2 = 1.124. 1,000 × 1.124 ≈ <b>1,124 lb</b>. Starts, stops and bounces always add load."},
{q:"Wind pressure on a 10 × 10 ft video wall at 60 mph, before any shape factor?",
  o:["About 92 lb","About 600 lb","About 920 lb","About 6,000 lb"],a:2,
  e:"q = 0.00256 × 60² ≈ 9.2 psf. 9.2 × 100 sq ft ≈ <b>920 lb</b> sideways — more once the shape factor for a flat panel is applied. That's why outdoor rigs run on a wind plan."},
{q:"OSHA's fall protection trigger height in general industry is:",
  o:["4 ft","6 ft","10 ft","15 ft"],a:0,
  e:"<b>4 ft</b> in general industry, 6 ft in construction, 10 ft on scaffolds. In the steel you are tied off 100% regardless."},
{q:"Someone yells “Headache!” while you're on the floor. You:",
  o:["Look up to see what's coming","Cover your head and move out from under the work without looking up","Freeze where you are","Yell it back and keep working"],a:1,
  e:"<b>Don't look up</b> — that puts your face in the path. Cover your head and move out from under the work."},
{q:"Hotel ballroom. The AV company wants a 300 lb speaker hung from a ceiling sprinkler pipe because it's close. You:",
  o:["Hang it — 300 lb is light","Refuse that attachment; use only the venue's rated points, through the house rigger","Use two sprinkler pipes to split the load","Use a bigger shackle"],a:1,
  e:"Sprinkler pipe, duct, conduit and ceiling grid are <b>not rated rigging points</b>. Rated points only, approved by the venue — usually through the house rigger."},
{q:"What's the best control on the hierarchy of controls?",
  o:["PPE","Administrative rules","Engineering controls","Eliminating the hazard"],a:3,
  e:"<b>Eliminate &rarr; substitute &rarr; engineer &rarr; administrative &rarr; PPE.</b> If you can do the work from the floor instead of at height, that beats any harness."},
{q:"OSHA must be notified of a work-related fatality within:",
  o:["8 hours","24 hours","72 hours","7 days"],a:0,
  e:"<b>8 hours</b> for a fatality. In-patient hospitalisation, amputation or loss of an eye: <b>24 hours</b>."}
];

var CHAINS=[
{t:"Arena point — chalk mark to loaded hook",
  s:["Mark the floor from the plot","Up rigger finds the steel, calls “Rope!”","Down rigger builds the bundle to the plot","Haul it up — nobody under it","Basket the beam with softeners and shackle it","Hang the motor, latch closed","Head rigger checks before it takes weight"],
  w:"The floor mark is the plot made real. Everything after it is about getting rated hardware to the right steel without anyone underneath, then having a second set of eyes before it takes weight."},
{t:"The load path — top to bottom (climbing motor)",
  s:["Building steel","Beam wrap with softeners","Shackle","Bridle apex or dead-hang steel","Motor hook","Chain motor","Truss","Fixture and its safety"],
  w:"Every link is rated, and the whole path is only as strong as the weakest one — including the building."},
{t:"Loading a counterweight set",
  s:["Agree the load with the loading gallery","Rope lock on, set at low trim","Load goes on the batten","Counterweight goes in the arbor","Spreader plates and locking plate on","Check balance with a hand on the line","Release the lock and fly it"],
  w:"Batten first, arbor second, so the set is never arbor-heavy while the lock is the only thing holding it."},
{t:"Unloading a counterweight set",
  s:["Bring the set to its loading position and lock it","Tell the gallery what's coming off","Counterweight out of the arbor","Load off the batten","Check balance before the lock comes off"],
  w:"The exact reverse of loading: arbor first, batten second. Pull the batten load first and you've built a runaway."},
{t:"Flying a truss",
  s:["Clear the floor under and around it","Bump each motor until the chains are taut","Lift a few inches and stop","Check level, every point, nothing snagged","Fly to trim keeping it level","Confirm trim and secure the controller"],
  w:"The stop a few inches up is where you catch a snag, a lagging motor or a bad point while the truss can still go straight back down."},
{t:"Going up in the steel",
  s:["Rescue plan agreed","Inspect harness and lanyard","Harness on, fitted, buddy-checked","Clip to a rated anchorage before you're exposed","Stay 100% tied off while moving"],
  w:"The rescue plan comes first because suspension trauma doesn't wait for someone to figure one out."}
];

var SCN=[
{w:"Arena · motor call",
  q:"Points are up and the motors are on. You bump motor 7 UP to take the slack — the chain runs DOWN. The motor tech is across the floor. What do you do?",
  a:"<b>Stop and leave it stopped.</b><br><br><b>1.</b> Don't “just use the other button”. A reversed motor is out of phase, and its <b>limit switches don't protect it</b> — it can two-block or run off its chain.<br><b>2.</b> Call it on the radio: “Motor 7 is running backwards.”<br><b>3.</b> The phase gets corrected at the controller or cable by whoever owns the motor system, then 7 is bumped again to confirm UP goes up.<br><b>4.</b> If one is reversed, check the others on that cable or channel before the truss goes anywhere."},
{w:"Arena · bridle point",
  q:"You built a bridle on the floor from the plot. Once it's up and the motor takes slack, the apex is hanging about 18 inches off the chalk mark toward beam A. What happened and what's the fix?",
  a:"<b>The legs aren't the lengths the plot asked for.</b> If the apex moved toward A, the A leg is too short or the B leg is too long.<br><br><b>1.</b> Don't drag the point over by hand or tag-line it into place — that changes the angles and the load on both legs.<br><b>2.</b> Let it back down, re-measure both legs including shackles and deck chain, and correct the length to the plot.<br><b>3.</b> If the plot math itself looks off, take it to the head rigger. Moving the apex changes each leg's share of the weight."},
{w:"Shop · load-out",
  q:"Packing round slings, you find a green one with a cut in the cover. You can see core yarns, but it's only an inch long. Your partner says it's fine for a basket. What do you do?",
  a:"<b>Tag it out.</b><br><br><b>1.</b> Exposed core yarns retire a round sling — the cover is what protects the core, and nobody can vouch for the rating now.<br><b>2.</b> Mark it clearly as out of service and keep it apart from good gear, so it doesn't get packed back by someone else.<br><b>3.</b> Tell the head rigger or shop lead so it's logged and replaced. A sling that “disappears” without a record usually comes back."},
{w:"Hotel ballroom · corporate general session",
  q:"The AV vendor wants to hang two 300 lb speakers and a small truss. There's no plot. They point at the sprinkler pipe and a ceiling grid. The client's in the room. What happens?",
  a:"<b>Nothing hangs until there are rated points.</b><br><br><b>1.</b> Sprinkler pipe, duct, conduit and ceiling grid are <b>not</b> rigging points, at any load.<br><b>2.</b> Ask for the house rigger or engineering. Hotels with rigging have rated points and usually their own rigger who must approve or do the hanging.<br><b>3.</b> If there are no rated points, the answer is ground support — towers or stands — not a creative attachment.<br><b>4.</b> Keep it quiet and professional in front of the client. “We need the house rigger's points for this” is the whole conversation."},
{w:"Theatre · strike",
  q:"A drop is being taken off a pipe at deck level. The deck crew has unclipped it and the pipe is empty. Someone is about to take the rope lock off to send the pipe out. The arbor still has the weight in it.",
  a:"<b>“Hold the lock!” — loudly, now.</b><br><br><b>1.</b> With the load gone and the weight still in, the set is badly <b>arbor-heavy</b>. Release the lock and the arbor falls and the pipe flies out — a runaway.<br><b>2.</b> The weight has to come out of the arbor at the loading gallery <b>before</b> the lock comes off.<br><b>3.</b> The right order was arbor first, then the drop. Get the gallery on headset, unload to balance, then check with a hand on the line."},
{w:"Arena · truss fly-out",
  q:"A 60 ft truss on six motors is a few feet off the floor. One end is clearly lower than the other and the chains on that end look slack. Load cells show the motors at the high end climbing.",
  a:"<b>Stop all motors.</b><br><br><b>1.</b> A lagging or stalled motor at the low end means the others are carrying its share — and the truss is racking.<br><b>2.</b> Find out why: tripped motor, wrong channel, slack chain, snag.<br><b>3.</b> Bring it back to level by bumping the low motors (or lowering the high ones) one at a time, watching the load cells even out.<br><b>4.</b> Then the few-inches-and-stop check again before it goes higher."},
{w:"Outdoor festival · weather",
  q:"The wind is building through the afternoon. A big video wall is flown on the ground-supported roof. Someone says it's fine because nothing is moving yet.",
  a:"<b>The wind plan decides, not how it looks.</b><br><br><b>1.</b> Wind load grows with the <b>square</b> of the speed: double the wind is four times the force. A 10 × 10 ft wall sees roughly 920 lb at 60 mph before shape factor.<br><b>2.</b> The structure has a written wind plan with speeds for watching, dropping soft goods and banners, landing the wall, and clearing the stage.<br><b>3.</b> Someone is watching an anemometer and calling it. Your job is to know which step you're on and to be ready before the number is reached, not after."},
{w:"Arena · in the steel",
  q:"You're up on a beam moving to the next point. Your lanyard won't reach the next anchor without unclipping for a second. The point is right there.",
  a:"<b>You don't unclip.</b><br><br><b>1.</b> 100% tie-off means always: use a twin-leg lanyard and clip the second leg before unclipping the first, or re-route on a beam strap or retractable that reaches.<br><b>2.</b> If you can't make the move without being unclipped, stop and ask — it's a planning problem, not a speed problem.<br><b>3.</b> Everybody else on the call wants you to take the extra 30 seconds."}
];

var CK=[
"Point number and type match the plot — dead hang or bridle, leg lengths, load",
"Every piece has a readable rating — shackles stamped, slings and steel tagged",
"Shackle pins fully seated; pins that stay up for the show are moused",
"Bridle legs in the bow of the apex shackle; included angle at or under 120°",
"Softeners on every beam edge the steel or sling touches",
"Deck chain shackled through a link — never hooked or knotted",
"Motor hook latch closed, chain not twisted, chain bag on and big enough",
"Motor bumped: UP goes up",
"Floor under the haul cleared; “Rope!” called before anything drops",
"Head rigger has checked the point before it takes weight"
];
